import type { Order } from "@/types/orders";

export const mockOrders: Order[] = [
  {
    orderId: "ORD-001",
    showId: "AWS23",
    occurrenceId: "AWS23-LV",
    subTotal: 15000,
    salesChannel: "Direct",
    terms: "Net 30",
    tax: 1500,
    orderType: "New",
    customerPO: "PO-12345",
    cancelCharge: 0,
    source: "Web",
    project: "P2024-001",
    orderDate: "2024-03-20",
    boothInfo: "Booth #A12",
    billingAddress: "123 Main St, New York, NY 10001",
    total: 16500,
    items: [
      {
        serialNo: 1,
        orderedItem: "Booth Package A",
        itemDescription: "Standard 10x10 Booth",
        quantity: 1,
        cancellationFee: 0,
        quantityCancelled: 0,
        uom: "EA",
        kitPrice: 3000,
        newPrice: 3000,
        discount: 0,
        extendedPrice: 3000,
        userItemDescription: "Standard booth with basic setup",
        dff: "N/A",
        orderReceivedDate: "2024-03-20",
        status: "Confirmed",
        itemType: "Booth",
        ato: false,
        lineType: "Standard",
        documentNumber: "DOC-001",
        industryInformation: "Technology",
      },
      {
        serialNo: 2,
        orderedItem: "LED Screen",
        itemDescription: "55-inch LED Display",
        quantity: 2,
        cancellationFee: 500,
        quantityCancelled: 0,
        uom: "EA",
        kitPrice: 2000,
        newPrice: 2000,
        discount: 0,
        extendedPrice: 4000,
        userItemDescription: "High-resolution display for presentations",
        dff: "N/A",
        orderReceivedDate: "2024-03-20",
        status: "Confirmed",
        itemType: "Equipment",
        ato: false,
        lineType: "Standard",
        documentNumber: "DOC-002",
        industryInformation: "Technology",
      },
      {
        serialNo: 3,
        orderedItem: "Furniture Package",
        itemDescription: "Basic Booth Furniture Set",
        quantity: 1,
        cancellationFee: 200,
        quantityCancelled: 0,
        uom: "SET",
        kitPrice: 8000,
        newPrice: 8000,
        discount: 0,
        extendedPrice: 8000,
        userItemDescription: "Includes table, chairs, and storage",
        dff: "N/A",
        orderReceivedDate: "2024-03-20",
        status: "Confirmed",
        itemType: "Furniture",
        ato: false,
        lineType: "Standard",
        documentNumber: "DOC-003",
        industryInformation: "Technology",
      }
    ]
  },
  {
    orderId: "ORD-002",
    showId: "MSFT24",
    occurrenceId: "BUILD24-SEA",
    subTotal: 25000,
    salesChannel: "Partner",
    terms: "Net 45",
    tax: 2500,
    orderType: "New",
    customerPO: "PO-23456",
    cancelCharge: 0,
    source: "Email",
    project: "P2024-002",
    orderDate: "2024-03-21",
    boothInfo: "Booth #B15",
    billingAddress: "456 Tech Ave, Seattle, WA 98101",
    total: 27500,
    items: [
      {
        serialNo: 1,
        orderedItem: "Premium Booth Package",
        itemDescription: "20x20 Premium Booth",
        quantity: 1,
        cancellationFee: 1000,
        quantityCancelled: 0,
        uom: "EA",
        kitPrice: 12000,
        newPrice: 12000,
        discount: 0,
        extendedPrice: 12000,
        userItemDescription: "Premium booth with custom branding",
        dff: "N/A",
        orderReceivedDate: "2024-03-21",
        status: "Confirmed",
        itemType: "Booth",
        ato: false,
        lineType: "Premium",
        documentNumber: "DOC-004",
        industryInformation: "Software",
      },
      {
        serialNo: 2,
        orderedItem: "AV Package",
        itemDescription: "Complete Audio-Visual Setup",
        quantity: 1,
        cancellationFee: 800,
        quantityCancelled: 0,
        uom: "SET",
        kitPrice: 8000,
        newPrice: 8000,
        discount: 0,
        extendedPrice: 8000,
        userItemDescription: "Includes sound system and projectors",
        dff: "N/A",
        orderReceivedDate: "2024-03-21",
        status: "Confirmed",
        itemType: "Equipment",
        ato: false,
        lineType: "Premium",
        documentNumber: "DOC-005",
        industryInformation: "Software",
      },
      {
        serialNo: 3,
        orderedItem: "Server Rack",
        itemDescription: "Enterprise Server Rack",
        quantity: 2,
        cancellationFee: 800,
        quantityCancelled: 0,
        uom: "EA",
        kitPrice: 8000,
        newPrice: 8000,
        discount: 0,
        extendedPrice: 16000,
        userItemDescription: "Enterprise-grade server racks",
        dff: "N/A",
        orderReceivedDate: "2024-03-21",
        status: "Confirmed",
        itemType: "Equipment",
        ato: false,
        lineType: "Premium",
        documentNumber: "DOC-006",
        industryInformation: "Cloud Computing",
      }
    ]
  },
  {
    orderId: "ORD-006",
    showId: "AWS23",
    occurrenceId: "AWS23-LV",
    subTotal: 35000,
    salesChannel: "Direct",
    terms: "Net 30",
    tax: 3500,
    orderType: "New",
    customerPO: "PO-67890",
    cancelCharge: 0,
    source: "Web",
    project: "P2024-006",
    orderDate: "2024-03-25",
    boothInfo: "Booth #F30",
    billingAddress: "555 Cloud Ave, Las Vegas, NV 89109",
    total: 38500,
    items: [
      {
        serialNo: 1,
        orderedItem: "Premium Booth Package",
        itemDescription: "20x20 Premium Booth",
        quantity: 1,
        cancellationFee: 1000,
        quantityCancelled: 0,
        uom: "EA",
        kitPrice: 12000,
        newPrice: 12000,
        discount: 0,
        extendedPrice: 12000,
        userItemDescription: "Premium booth with custom branding",
        dff: "N/A",
        orderReceivedDate: "2024-03-25",
        status: "Confirmed",
        itemType: "Booth",
        ato: false,
        lineType: "Premium",
        documentNumber: "DOC-016",
        industryInformation: "Cloud Computing",
      },
      {
        serialNo: 2,
        orderedItem: "Server Rack",
        itemDescription: "Enterprise Server Rack",
        quantity: 2,
        cancellationFee: 800,
        quantityCancelled: 0,
        uom: "EA",
        kitPrice: 8000,
        newPrice: 8000,
        discount: 0,
        extendedPrice: 16000,
        userItemDescription: "Enterprise-grade server racks",
        dff: "N/A",
        orderReceivedDate: "2024-03-25",
        status: "Confirmed",
        itemType: "Equipment",
        ato: false,
        lineType: "Premium",
        documentNumber: "DOC-017",
        industryInformation: "Cloud Computing",
      },
      {
        serialNo: 3,
        orderedItem: "Network Infrastructure",
        itemDescription: "Complete Network Setup",
        quantity: 1,
        cancellationFee: 600,
        quantityCancelled: 0,
        uom: "SET",
        kitPrice: 7000,
        newPrice: 7000,
        discount: 0,
        extendedPrice: 7000,
        userItemDescription: "Complete network infrastructure setup",
        dff: "N/A",
        orderReceivedDate: "2024-03-25",
        status: "Confirmed",
        itemType: "Equipment",
        ato: false,
        lineType: "Premium",
        documentNumber: "DOC-018",
        industryInformation: "Cloud Computing",
      }
    ]
  },
  {
    orderId: "ORD-007",
    showId: "MSFT24",
    occurrenceId: "BUILD24-SEA",
    subTotal: 28000,
    salesChannel: "Partner",
    terms: "Net 45",
    tax: 2800,
    orderType: "New",
    customerPO: "PO-78901",
    cancelCharge: 0,
    source: "Email",
    project: "P2024-007",
    orderDate: "2024-03-26",
    boothInfo: "Booth #G35",
    billingAddress: "777 Dev Street, Seattle, WA 98101",
    total: 30800,
    items: [
      {
        serialNo: 1,
        orderedItem: "Standard Booth Package",
        itemDescription: "10x10 Standard Booth",
        quantity: 1,
        cancellationFee: 0,
        quantityCancelled: 0,
        uom: "EA",
        kitPrice: 5000,
        newPrice: 5000,
        discount: 0,
        extendedPrice: 5000,
        userItemDescription: "Standard booth setup",
        dff: "N/A",
        orderReceivedDate: "2024-03-26",
        status: "Confirmed",
        itemType: "Booth",
        ato: false,
        lineType: "Standard",
        documentNumber: "DOC-019",
        industryInformation: "Software Development",
      },
      {
        serialNo: 2,
        orderedItem: "Developer Workstations",
        itemDescription: "High-Performance Workstations",
        quantity: 4,
        cancellationFee: 300,
        quantityCancelled: 0,
        uom: "EA",
        kitPrice: 3000,
        newPrice: 3000,
        discount: 0,
        extendedPrice: 12000,
        userItemDescription: "Developer workstations with dual monitors",
        dff: "N/A",
        orderReceivedDate: "2024-03-26",
        status: "Confirmed",
        itemType: "Equipment",
        ato: false,
        lineType: "Standard",
        documentNumber: "DOC-020",
        industryInformation: "Software Development",
      },
      {
        serialNo: 3,
        orderedItem: "Demo Area Setup",
        itemDescription: "Interactive Demo Area",
        quantity: 1,
        cancellationFee: 500,
        quantityCancelled: 0,
        uom: "SET",
        kitPrice: 11000,
        newPrice: 11000,
        discount: 0,
        extendedPrice: 11000,
        userItemDescription: "Interactive demo area with touch screens",
        dff: "N/A",
        orderReceivedDate: "2024-03-26",
        status: "Confirmed",
        itemType: "Equipment",
        ato: false,
        lineType: "Standard",
        documentNumber: "DOC-021",
        industryInformation: "Software Development",
      }
    ]
  },
  {
    orderId: "ORD-008",
    showId: "GGL24",
    occurrenceId: "IO24-SF",
    subTotal: 42000,
    salesChannel: "Direct",
    terms: "Net 30",
    tax: 4200,
    orderType: "New",
    customerPO: "PO-89012",
    cancelCharge: 0,
    source: "Web",
    project: "P2024-008",
    orderDate: "2024-03-27",
    boothInfo: "Booth #H40",
    billingAddress: "888 Innovation Drive, San Francisco, CA 94105",
    total: 46200,
    items: [
      {
        serialNo: 1,
        orderedItem: "Deluxe Booth Package",
        itemDescription: "30x30 Deluxe Booth",
        quantity: 1,
        cancellationFee: 1500,
        quantityCancelled: 0,
        uom: "EA",
        kitPrice: 15000,
        newPrice: 15000,
        discount: 0,
        extendedPrice: 15000,
        userItemDescription: "Deluxe booth with premium features",
        dff: "N/A",
        orderReceivedDate: "2024-03-27",
        status: "Confirmed",
        itemType: "Booth",
        ato: false,
        lineType: "Deluxe",
        documentNumber: "DOC-022",
        industryInformation: "Technology",
      },
      {
        serialNo: 2,
        orderedItem: "Meeting Rooms",
        itemDescription: "Private Meeting Rooms",
        quantity: 2,
        cancellationFee: 1000,
        quantityCancelled: 0,
        uom: "EA",
        kitPrice: 8000,
        newPrice: 8000,
        discount: 0,
        extendedPrice: 16000,
        userItemDescription: "Private meeting rooms with AV",
        dff: "N/A",
        orderReceivedDate: "2024-03-27",
        status: "Confirmed",
        itemType: "Room",
        ato: false,
        lineType: "Deluxe",
        documentNumber: "DOC-023",
        industryInformation: "Technology",
      },
      {
        serialNo: 3,
        orderedItem: "Lounge Area",
        itemDescription: "VIP Lounge Setup",
        quantity: 1,
        cancellationFee: 800,
        quantityCancelled: 0,
        uom: "EA",
        kitPrice: 11000,
        newPrice: 11000,
        discount: 0,
        extendedPrice: 11000,
        userItemDescription: "VIP lounge with premium furniture",
        dff: "N/A",
        orderReceivedDate: "2024-03-27",
        status: "Confirmed",
        itemType: "Furniture",
        ato: false,
        lineType: "Deluxe",
        documentNumber: "DOC-024",
        industryInformation: "Technology",
      }
    ]
  },
  {
    orderId: "ORD-009",
    showId: "WWDC24",
    occurrenceId: "WWDC24-CUP",
    subTotal: 19000,
    salesChannel: "Direct",
    terms: "Net 30",
    tax: 1900,
    orderType: "New",
    customerPO: "PO-90123",
    cancelCharge: 0,
    source: "Web",
    project: "P2024-009",
    orderDate: "2024-03-28",
    boothInfo: "Booth #I45",
    billingAddress: "999 Apple Way, Cupertino, CA 95014",
    total: 20900,
    items: [
      {
        serialNo: 1,
        orderedItem: "Standard Booth Package",
        itemDescription: "10x10 Standard Booth",
        quantity: 1,
        cancellationFee: 0,
        quantityCancelled: 0,
        uom: "EA",
        kitPrice: 5000,
        newPrice: 5000,
        discount: 0,
        extendedPrice: 5000,
        userItemDescription: "Standard booth setup",
        dff: "N/A",
        orderReceivedDate: "2024-03-28",
        status: "Confirmed",
        itemType: "Booth",
        ato: false,
        lineType: "Standard",
        documentNumber: "DOC-025",
        industryInformation: "Technology",
      },
      {
        serialNo: 2,
        orderedItem: "Display Monitors",
        itemDescription: "27-inch 4K Monitors",
        quantity: 4,
        cancellationFee: 200,
        quantityCancelled: 0,
        uom: "EA",
        kitPrice: 800,
        newPrice: 800,
        discount: 0,
        extendedPrice: 3200,
        userItemDescription: "High-resolution monitors for demos",
        dff: "N/A",
        orderReceivedDate: "2024-03-28",
        status: "Confirmed",
        itemType: "Equipment",
        ato: false,
        lineType: "Standard",
        documentNumber: "DOC-026",
        industryInformation: "Technology",
      },
      {
        serialNo: 3,
        orderedItem: "Demo Stations",
        itemDescription: "Interactive Demo Stations",
        quantity: 3,
        cancellationFee: 400,
        quantityCancelled: 0,
        uom: "EA",
        kitPrice: 4000,
        newPrice: 4000,
        discount: 0,
        extendedPrice: 12000,
        userItemDescription: "Interactive demo stations with touch screens",
        dff: "N/A",
        orderReceivedDate: "2024-03-28",
        status: "Confirmed",
        itemType: "Equipment",
        ato: false,
        lineType: "Standard",
        documentNumber: "DOC-027",
        industryInformation: "Technology",
      }
    ]
  },
  {
    orderId: "ORD-010",
    showId: "CES24",
    occurrenceId: "CES24-LV",
    subTotal: 45000,
    salesChannel: "Partner",
    terms: "Net 45",
    tax: 4500,
    orderType: "New",
    customerPO: "PO-01234",
    cancelCharge: 0,
    source: "Email",
    project: "P2024-010",
    orderDate: "2024-03-29",
    boothInfo: "Booth #J50",
    billingAddress: "111 Tech Lane, Las Vegas, NV 89109",
    total: 49500,
    items: [
      {
        serialNo: 1,
        orderedItem: "Premium Booth Package",
        itemDescription: "20x20 Premium Booth",
        quantity: 1,
        cancellationFee: 1000,
        quantityCancelled: 0,
        uom: "EA",
        kitPrice: 12000,
        newPrice: 12000,
        discount: 0,
        extendedPrice: 12000,
        userItemDescription: "Premium booth with custom branding",
        dff: "N/A",
        orderReceivedDate: "2024-03-29",
        status: "Confirmed",
        itemType: "Booth",
        ato: false,
        lineType: "Premium",
        documentNumber: "DOC-028",
        industryInformation: "Consumer Electronics",
      },
      {
        serialNo: 2,
        orderedItem: "Product Display Cases",
        itemDescription: "Premium Display Cases",
        quantity: 6,
        cancellationFee: 200,
        quantityCancelled: 0,
        uom: "EA",
        kitPrice: 2500,
        newPrice: 2500,
        discount: 0,
        extendedPrice: 15000,
        userItemDescription: "Premium display cases with lighting",
        dff: "N/A",
        orderReceivedDate: "2024-03-29",
        status: "Confirmed",
        itemType: "Furniture",
        ato: false,
        lineType: "Premium",
        documentNumber: "DOC-029",
        industryInformation: "Consumer Electronics",
      },
      {
        serialNo: 3,
        orderedItem: "Lighting Package",
        itemDescription: "Professional Lighting Setup",
        quantity: 1,
        cancellationFee: 300,
        quantityCancelled: 0,
        uom: "SET",
        kitPrice: 18000,
        newPrice: 18000,
        discount: 0,
        extendedPrice: 18000,
        userItemDescription: "Professional lighting for product display",
        dff: "N/A",
        orderReceivedDate: "2024-03-29",
        status: "Confirmed",
        itemType: "Equipment",
        ato: false,
        lineType: "Premium",
        documentNumber: "DOC-030",
        industryInformation: "Consumer Electronics",
      }
    ]
  }
]; 