// Here is the complete mock data with 10 orders fully structured! 

const orders = [
  {
    orderId: "3478019",
    status: "Closed",
    customer: "3ARM",
    salesChannel: "EXHIBITOR",
    terms: "IMMED",
    orderType: "Freight Order",
    customerPo: "EDB8F-5D62B",
    source: "GES Experience",
    project: "071671301",
    booth: "S2885 - PROMAT_201704 - 3ARM",
    orderDate: "02/20/2017",
    subtotal: 209.43,
    tax: 0,
    cancelCharge: 0,
    total: 209.43,
    billToAddress1: "POLIND PLA DELS VIN",
    billToAddress2: "SANT JOAN DE VILATORRADA",
    lineItems: [
      { line: "1.1", orderedItem: "200400", itemDescription: "ESTIMATED MATERIAL HANDLING", qty: 1, cancellationFee: "", qtyCancelled: 0, uom: "EA", kitPrice: 0, newPrice: 837.72, discount: "", extendedPrice: 837.72, userItemDescription: "", dff: "||||||||No" },
      { line: "2.1", orderedItem: "200400", itemDescription: "ESTIMATED MATERIAL HANDLING", qty: 1, cancellationFee: "", qtyCancelled: 0, uom: "EA", kitPrice: -837.72, newPrice: -837.72, discount: "", extendedPrice: -837.72, userItemDescription: "", dff: "|No" },
      { line: "3.1", orderedItem: "200500", itemDescription: "EXHIBIT MATERIAL HANDLING", qty: 3, cancellationFee: "", qtyCancelled: 0, uom: "SSC", kitPrice: 69.81, newPrice: 69.81, discount: "", extendedPrice: 209.43, userItemDescription: "", dff: "||2.50" },
    ],
  },
  {
    orderId: "3478024",
    status: "Closed",
    customer: "Google",
    salesChannel: "EXHIBITOR",
    terms: "IMMED",
    orderType: "Freight Order",
    customerPo: "PO-10006",
    source: "Google Summit",
    project: "071671306",
    booth: "S3400",
    orderDate: "03/01/2025",
    subtotal: 500,
    tax: 30,
    cancelCharge: 0,
    total: 530,
    billToAddress1: "1600 Amphitheatre Pkwy",
    billToAddress2: "Mountain View, CA",
    lineItems: [
      {
        line: "1.1",
        orderedItem: "700100",
        itemDescription: "GOOGLE HANDLING",
        qty: 5,
        cancellationFee: "",
        qtyCancelled: 0,
        uom: "EA",
        kitPrice: 100,
        newPrice: 120,
        discount: "",
        extendedPrice: 480,
        userItemDescription: "",
        dff: "",
      },
    ],
  },
  {
    orderId: "3478025",
    status: "Pending",
    customer: "Meta",
    salesChannel: "EXHIBITOR",
    terms: "NET30",
    orderType: "Freight Order",
    customerPo: "PO-10007",
    source: "Meta Connect",
    project: "071671307",
    booth: "S3501",
    orderDate: "  03/05/2025",
    subtotal: 600,
    tax: 35,
    cancelCharge: 0,
    total: 635,
    billToAddress1: "1 Hacker Way",
    billToAddress2: "Menlo Park, CA",
    lineItems: [
      {
        line: "1.1",
        orderedItem: "700101",
        itemDescription: "META HANDLING",
        qty: 1,
        cancellationFee: "",
        qtyCancelled: 0,
        uom: "EA",
        kitPrice: 110,
        newPrice: 135,
        discount: "",
        extendedPrice: 560,
        userItemDescription: "",
        dff: "",
      },
    ],
  },
  {
    orderId: "3478026",
    status: "Confirmed",
    customer: "Netflix",
    salesChannel: "EXHIBITOR",
    terms: "NET15",
    orderType: "Freight Order",
    customerPo: "PO-10008",
    source: "Netflix Fest",
    project: "071671308",
    booth: "S3602",
    orderDate: "01/28/2025",
    subtotal: 700,
    tax: 40,
    cancelCharge: 0,
    total: 740,
    billToAddress1: "100 Winchester Cir",
    billToAddress2: "Los Gatos, CA",
    lineItems: [
      {
        line: "1.1",
        orderedItem: "700102",
        itemDescription: "NETFLIX HANDLING",
        qty: 5,
        cancellationFee: "",
        qtyCancelled: 0,
        uom: "EA",
        kitPrice: 120,
        newPrice: 150,
        discount: "",
        extendedPrice: 640,
        userItemDescription: "",
        dff: "",
      },
    ],
  },
  {
    orderId: "3478027",
    status: "Confirmed",
    customer: "IBM",
    salesChannel: "EXHIBITOR",
    terms: "NET15",
    orderType: "Freight Order",
    customerPo: "PO-10009",
    source: "IBM Think",
    project: "071671309",
    booth: "S3703",
    orderDate: "04/16/2025",
    subtotal: 800,
    tax: 45,
    cancelCharge: 0,
    total: 845,
    billToAddress1: "1 New Orchard Rd",
    billToAddress2: "Armonk, NY",
    lineItems: [
      {
        line: "1.1",
        orderedItem: "700103",
        itemDescription: "IBM HANDLING",
        qty: 2,
        cancellationFee: "",
        qtyCancelled: 0,
        uom: "EA",
        kitPrice: 130,
        newPrice: 165,
        discount: "",
        extendedPrice: 720,
        userItemDescription: "",
        dff: "",
      },
    ],
  },
  {
    orderId: "3478028",
    status: "Closed",
    customer: "Intel",
    salesChannel: "EXHIBITOR",
    terms: "NET30",
    orderType: "Freight Order",
    customerPo: "PO-100010",
    source: "Intel Expo",
    project: "071671310",
    booth: "S3804",
    orderDate: "01/30/2025",
    subtotal: 900,
    tax: 50,
    cancelCharge: 0,
    total: 950,
    billToAddress1: "2200 Mission College Blvd",
    billToAddress2: "Santa Clara, CA",
    lineItems: [
      {
        line: "1.1",
        orderedItem: "700104",
        itemDescription: "INTEL HANDLING",
        qty: 4,
        cancellationFee: "",
        qtyCancelled: 0,
        uom: "EA",
        kitPrice: 140,
        newPrice: 180,
        discount: "",
        extendedPrice: 800,
        userItemDescription: "",
        dff: "",
      },
    ],
  }, 
  {
    orderId: "3478020",
    status: "Confirmed",
    customer: "Microsoft",
    salesChannel: "DIRECT",
    terms: "NET30",
    orderType: "Freight Order",
    customerPo: "PO-10002",
    source: "Microsoft Experience",
    project: "071671302",
    booth: "S2901",
    orderDate: "04/15/2024",
    subtotal: 500,
    tax: 50,
    cancelCharge: 0,
    total: 550,
    billToAddress1: "1 Microsoft Way",
    billToAddress2: "Redmond, WA",
    lineItems: [
      { line: "1.1", orderedItem: "300100", itemDescription: "DISPLAY MATERIAL HANDLING", qty: 2, cancellationFee: "", qtyCancelled: 0, uom: "EA", kitPrice: 200, newPrice: 220, discount: "", extendedPrice: 440, userItemDescription: "", dff: "|Yes" },
    ],
  },
  {
    orderId: "3478021",
    status: "Pending",
    customer: "Amazon",
    salesChannel: "EXHIBITOR",
    terms: "IMMED",
    orderType: "Express Order",
    customerPo: "PO-10003",
    source: "Amazon Expo",
    project: "071671303",
    booth: "S3002",
    orderDate: "04/20/2024",
    subtotal: 620,
    tax: 30,
    cancelCharge: 0,
    total: 650,
    billToAddress1: "410 Terry Ave",
    billToAddress2: "Seattle, WA",
    lineItems: [
      { line: "1.1", orderedItem: "400100", itemDescription: "FURNITURE HANDLING", qty: 3, cancellationFee: "", qtyCancelled: 0, uom: "EA", kitPrice: 100, newPrice: 110, discount: "", extendedPrice: 330, userItemDescription: "", dff: "" },
      { line: "2.1", orderedItem: "400200", itemDescription: "STORAGE RENTAL", qty: 2, cancellationFee: "", qtyCancelled: 0, uom: "EA", kitPrice: 145, newPrice: 150, discount: "", extendedPrice: 300, userItemDescription: "", dff: "" },
    ],
  },
  {
    orderId: "3478022",
    status: "Closed",
    customer: "Apple",
    salesChannel: "EXHIBITOR",
    terms: "NET15",
    orderType: "Freight Order",
    customerPo: "PO-10004",
    source: "Apple World",
    project: "071671304",
    booth: "S3100",
    orderDate: "2024-03-10",
    subtotal: 900,
    tax: 60,
    cancelCharge: 0,
    total: 960,
    billToAddress1: "1 Infinite Loop",
    billToAddress2: "Cupertino, CA",
    lineItems: [
      { line: "1.1", orderedItem: "500100", itemDescription: "ELECTRICAL HANDLING", qty: 5, cancellationFee: "", qtyCancelled: 0, uom: "EA", kitPrice: 150, newPrice: 160, discount: "", extendedPrice: 800, userItemDescription: "", dff: "" },
    ],
  },
  {
    orderId: "3478023",
    status: "Confirmed",
    customer: "Tesla",
    salesChannel: "EXHIBITOR",
    terms: "IMMED",
    orderType: "Freight Order",
    customerPo: "PO-10005",
    source: "Tesla Expo",
    project: "071671305",
    booth: "S3305",
    orderDate: "2024-06-11",
    subtotal: 720,
    tax: 40,
    cancelCharge: 0,
    total: 760,
    billToAddress1: "3500 Deer Creek",
    billToAddress2: "Palo Alto, CA",
    lineItems: [
      { line: "1.1", orderedItem: "600100", itemDescription: "AV PACKAGE HANDLING", qty: 1, cancellationFee: "", qtyCancelled: 0, uom: "EA", kitPrice: 720, newPrice: 760, discount: "", extendedPrice: 760, userItemDescription: "", dff: "" },
    ],
  },
 
];

export default orders; 